export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN'
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN'
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN'

export default {
  SIGN_IN_SCREEN,
  SIGN_UP_SCREEN,
  FORGOT_PASSWORD_SCREEN,
}
